kind: pipeline
name: backend-auth
clone:
  depth: 5
steps:
  - name: submodule
    image: plugins/git
    settings:
      recursive: true
      submodule_override:
        backend-auth: 'https://git.makerforce.io/beep/backend-auth.git'
  - name: docker
    image: plugins/docker
    settings:
      registry: registry.makerforce.io
      repo: registry.makerforce.io/beep/backend-auth
      context: backend-subscribe
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
kind: pipeline
name: backend-bite
clone:
  depth: 5
steps:
  - name: submodule
    image: plugins/git
    settings:
      recursive: true
      submodule_override:
        backend-auth: 'https://git.makerforce.io/beep/backend-bite.git'
  - name: docker
    image: plugins/docker
    settings:
      registry: registry.makerforce.io
      repo: registry.makerforce.io/beep/backend-bite
      context: backend-subscribe
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
kind: pipeline
name: backend-core
clone:
  depth: 5
steps:
  - name: submodule
    image: plugins/git
    settings:
      recursive: true
      submodule_override:
        backend-auth: 'https://git.makerforce.io/beep/backend-core.git'
  - name: docker
    image: plugins/docker
    settings:
      registry: registry.makerforce.io
      repo: registry.makerforce.io/beep/backend-core
      context: backend-subscribe
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
kind: pipeline
name: backend-heartbeat
clone:
  depth: 5
steps:
  - name: submodule
    image: plugins/git
    settings:
      recursive: true
      submodule_override:
        backend-auth: 'https://git.makerforce.io/beep/backend-heartbeat.git'
  - name: docker
    image: plugins/docker
    settings:
      registry: registry.makerforce.io
      repo: registry.makerforce.io/beep/backend-heartbeat
      context: backend-subscribe
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
kind: pipeline
name: backend-login
clone:
  depth: 5
steps:
  - name: submodule
    image: plugins/git
    settings:
      recursive: true
      submodule_override:
        backend-auth: 'https://git.makerforce.io/beep/backend-login.git'
  - name: docker
    image: plugins/docker
    settings:
      registry: registry.makerforce.io
      repo: registry.makerforce.io/beep/backend-login
      context: backend-subscribe
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
kind: pipeline
name: backend-publish
clone:
  depth: 5
steps:
  - name: submodule
    image: plugins/git
    settings:
      recursive: true
      submodule_override:
        backend-auth: 'https://git.makerforce.io/beep/backend-publish.git'
  - name: docker
    image: plugins/docker
    settings:
      registry: registry.makerforce.io
      repo: registry.makerforce.io/beep/backend-publish
      context: backend-subscribe
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
kind: pipeline
name: backend-signal
clone:
  depth: 5
steps:
  - name: submodule
    image: plugins/git
    settings:
      recursive: true
      submodule_override:
        backend-auth: 'https://git.makerforce.io/beep/backend-signal.git'
  - name: docker
    image: plugins/docker
    settings:
      registry: registry.makerforce.io
      repo: registry.makerforce.io/beep/backend-signal
      context: backend-subscribe
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
kind: pipeline
name: backend-store
clone:
  depth: 5
steps:
  - name: submodule
    image: plugins/git
    settings:
      recursive: true
      submodule_override:
        backend-auth: 'https://git.makerforce.io/beep/backend-store.git'
  - name: docker
    image: plugins/docker
    settings:
      registry: registry.makerforce.io
      repo: registry.makerforce.io/beep/backend-store
      context: backend-subscribe
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
kind: pipeline
name: backend-subscribe
clone:
  depth: 5
steps:
  - name: submodule
    image: plugins/git
    settings:
      recursive: true
      submodule_override:
        backend-auth: 'https://git.makerforce.io/beep/backend-subscribe.git'
  - name: docker
    image: plugins/docker
    settings:
      registry: registry.makerforce.io
      repo: registry.makerforce.io/beep/backend-subscribe
      context: backend-subscribe
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
kind: pipeline
name: backend-transcription
clone:
  depth: 5
steps:
  - name: submodule
    image: plugins/git
    settings:
      recursive: true
      submodule_override:
        backend-auth: 'https://git.makerforce.io/beep/backend-transcription.git'
  - name: docker
    image: plugins/docker
    settings:
      registry: registry.makerforce.io
      repo: registry.makerforce.io/beep/backend-transcription
      context: backend-subscribe
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
