kind: pipeline
name: ssh-test
steps:
  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host: staging.beepvoice.app
      username: core
      key:
        from_secret: ssh_key
      script:
        - cd /home/core/staging && ls
trigger:
  branch:
    - master
  event:
    - push
    - tag
    - promote
    - rollback
---
kind: pipeline
name: call-self
steps:
  - name: regenrate
    image: 'node:12-alpine'
    commands:
      - yarn install
      - yarn generate
  - name: push-or-fail
    image: appleboy/drone-git-push
    settings:
      remote_name: origin
      branch: '${DRONE_SOURCE_BRANCH}'
      key:
        from_secret: push_ssh_key
      commit: true
      commit_message: '[SKIP CI] Automatically updating .drone.yml'
    failure: ignore
trigger:
  branch:
    - master
  event:
    - pull_request
---
kind: pipeline
name: deploy
steps:
  - name: submodule
    image: plugins/git
    settings:
      recursive: true
      submodule_override:
        backend-core: 'https://git.makerforce.io/beep/backend-core.git'
        backend-store: 'https://git.makerforce.io/beep/backend-store.git'
        backend-transcription: 'https://git.makerforce.io/beep/backend-transcription.git'
        backend-login: 'https://git.makerforce.io/beep/backend-login.git'
        backend-heartbeat: 'https://git.makerforce.io/beep/backend-heartbeat.git'
        backend-auth: 'https://git.makerforce.io/beep/backend-auth.git'
        backend-pictures: 'https://git.makerforce.io/beep/backend-pictures.git'
        backend-permissions: 'https://git.makerforce.io/beep/backend-permissions.git'
        backend-webrtc: 'https://git.makerforce.io/beep/backend-webrtc.git'
  - name: copy-docker-compose
    image: appleboy/drone-scp
    settings:
      host: staging.beepvoice.app
      username: core
      key:
        from_secret: ssh_key
      source:
        - docker-compose.staging.yml
        - traefik.staging.toml
      target: /home/core/staging
  - name: copy-migrations
    image: appleboy/drone-scp
    settings:
      host: staging.beepvoice.app
      username: core
      key:
        from_secret: ssh_key
      source:
        - backend-core/postgres/*
      target: /home/core/staging
  - name: docker-compose-up
    image: appleboy/drone-ssh
    settings:
      host: staging.beepvoice.app
      username: core
      key:
        from_secret: ssh_key
      script:
        - >-
          cd /home/core/staging && /home/core/docker-compose -f
          docker-compose.staging.yml pull
        - >-
          cd /home/core/staging && /home/core/docker-compose -f
          docker-compose.staging.yml up -d
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_beep
trigger:
  branch:
    - master
  event:
    - push
    - tag
    - promote
    - rollback
depends_on: []
