kind: pipeline
name: ssh-test
clone:
  depth: 1
steps:
  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host: staging.beepvoice.app
      username: core
      key:
        from_secret: ssh_key
      script:
        - cd /home/core/staging && ls
---
kind: pipeline
name: backend-auth
clone:
  depth: 1
steps:
  - name: submodule
    image: plugins/git
    settings:
      recursive: true
      submodule_override:
        backend-auth: 'https://git.makerforce.io/beep/backend-auth.git'
        backend-bite: 'https://git.makerforce.io/beep/backend-bite.git'
        backend-core: 'https://git.makerforce.io/beep/backend-core.git'
        backend-heartbeat: 'https://git.makerforce.io/beep/backend-heartbeat.git'
        backend-login: 'https://git.makerforce.io/beep/backend-login.git'
        backend-protobuf: 'https://git.makerforce.io/beep/backend-protobuf.git'
        backend-publish: 'https://git.makerforce.io/beep/backend-publish.git'
        backend-signal: 'https://git.makerforce.io/beep/backend-signal.git'
        backend-store: 'https://git.makerforce.io/beep/backend-store.git'
        backend-subscribe: 'https://git.makerforce.io/beep/backend-subscribe.git'
        backend-transcription: 'https://git.makerforce.io/beep/backend-transcription.git'
  - name: docker
    image: plugins/docker
    settings:
      registry: registry.makerforce.io
      repo: registry.makerforce.io/beep/backend-auth
      context: backend-auth
      dockerfile: backend-auth/Dockerfile
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
---
kind: pipeline
name: backend-bite
clone:
  depth: 1
steps:
  - name: submodule
    image: plugins/git
    settings:
      recursive: true
      submodule_override:
        backend-auth: 'https://git.makerforce.io/beep/backend-auth.git'
        backend-bite: 'https://git.makerforce.io/beep/backend-bite.git'
        backend-core: 'https://git.makerforce.io/beep/backend-core.git'
        backend-heartbeat: 'https://git.makerforce.io/beep/backend-heartbeat.git'
        backend-login: 'https://git.makerforce.io/beep/backend-login.git'
        backend-protobuf: 'https://git.makerforce.io/beep/backend-protobuf.git'
        backend-publish: 'https://git.makerforce.io/beep/backend-publish.git'
        backend-signal: 'https://git.makerforce.io/beep/backend-signal.git'
        backend-store: 'https://git.makerforce.io/beep/backend-store.git'
        backend-subscribe: 'https://git.makerforce.io/beep/backend-subscribe.git'
        backend-transcription: 'https://git.makerforce.io/beep/backend-transcription.git'
  - name: docker
    image: plugins/docker
    settings:
      registry: registry.makerforce.io
      repo: registry.makerforce.io/beep/backend-bite
      context: backend-bite
      dockerfile: backend-bite/Dockerfile
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
---
kind: pipeline
name: backend-core
clone:
  depth: 1
steps:
  - name: submodule
    image: plugins/git
    settings:
      recursive: true
      submodule_override:
        backend-auth: 'https://git.makerforce.io/beep/backend-auth.git'
        backend-bite: 'https://git.makerforce.io/beep/backend-bite.git'
        backend-core: 'https://git.makerforce.io/beep/backend-core.git'
        backend-heartbeat: 'https://git.makerforce.io/beep/backend-heartbeat.git'
        backend-login: 'https://git.makerforce.io/beep/backend-login.git'
        backend-protobuf: 'https://git.makerforce.io/beep/backend-protobuf.git'
        backend-publish: 'https://git.makerforce.io/beep/backend-publish.git'
        backend-signal: 'https://git.makerforce.io/beep/backend-signal.git'
        backend-store: 'https://git.makerforce.io/beep/backend-store.git'
        backend-subscribe: 'https://git.makerforce.io/beep/backend-subscribe.git'
        backend-transcription: 'https://git.makerforce.io/beep/backend-transcription.git'
  - name: docker
    image: plugins/docker
    settings:
      registry: registry.makerforce.io
      repo: registry.makerforce.io/beep/backend-core
      context: backend-core
      dockerfile: backend-core/Dockerfile
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
---
kind: pipeline
name: backend-heartbeat
clone:
  depth: 1
steps:
  - name: submodule
    image: plugins/git
    settings:
      recursive: true
      submodule_override:
        backend-auth: 'https://git.makerforce.io/beep/backend-auth.git'
        backend-bite: 'https://git.makerforce.io/beep/backend-bite.git'
        backend-core: 'https://git.makerforce.io/beep/backend-core.git'
        backend-heartbeat: 'https://git.makerforce.io/beep/backend-heartbeat.git'
        backend-login: 'https://git.makerforce.io/beep/backend-login.git'
        backend-protobuf: 'https://git.makerforce.io/beep/backend-protobuf.git'
        backend-publish: 'https://git.makerforce.io/beep/backend-publish.git'
        backend-signal: 'https://git.makerforce.io/beep/backend-signal.git'
        backend-store: 'https://git.makerforce.io/beep/backend-store.git'
        backend-subscribe: 'https://git.makerforce.io/beep/backend-subscribe.git'
        backend-transcription: 'https://git.makerforce.io/beep/backend-transcription.git'
  - name: docker
    image: plugins/docker
    settings:
      registry: registry.makerforce.io
      repo: registry.makerforce.io/beep/backend-heartbeat
      context: backend-heartbeat
      dockerfile: backend-heartbeat/Dockerfile
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
---
kind: pipeline
name: backend-login
clone:
  depth: 1
steps:
  - name: submodule
    image: plugins/git
    settings:
      recursive: true
      submodule_override:
        backend-auth: 'https://git.makerforce.io/beep/backend-auth.git'
        backend-bite: 'https://git.makerforce.io/beep/backend-bite.git'
        backend-core: 'https://git.makerforce.io/beep/backend-core.git'
        backend-heartbeat: 'https://git.makerforce.io/beep/backend-heartbeat.git'
        backend-login: 'https://git.makerforce.io/beep/backend-login.git'
        backend-protobuf: 'https://git.makerforce.io/beep/backend-protobuf.git'
        backend-publish: 'https://git.makerforce.io/beep/backend-publish.git'
        backend-signal: 'https://git.makerforce.io/beep/backend-signal.git'
        backend-store: 'https://git.makerforce.io/beep/backend-store.git'
        backend-subscribe: 'https://git.makerforce.io/beep/backend-subscribe.git'
        backend-transcription: 'https://git.makerforce.io/beep/backend-transcription.git'
  - name: docker
    image: plugins/docker
    settings:
      registry: registry.makerforce.io
      repo: registry.makerforce.io/beep/backend-login
      context: backend-login
      dockerfile: backend-login/Dockerfile
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
---
kind: pipeline
name: backend-publish
clone:
  depth: 1
steps:
  - name: submodule
    image: plugins/git
    settings:
      recursive: true
      submodule_override:
        backend-auth: 'https://git.makerforce.io/beep/backend-auth.git'
        backend-bite: 'https://git.makerforce.io/beep/backend-bite.git'
        backend-core: 'https://git.makerforce.io/beep/backend-core.git'
        backend-heartbeat: 'https://git.makerforce.io/beep/backend-heartbeat.git'
        backend-login: 'https://git.makerforce.io/beep/backend-login.git'
        backend-protobuf: 'https://git.makerforce.io/beep/backend-protobuf.git'
        backend-publish: 'https://git.makerforce.io/beep/backend-publish.git'
        backend-signal: 'https://git.makerforce.io/beep/backend-signal.git'
        backend-store: 'https://git.makerforce.io/beep/backend-store.git'
        backend-subscribe: 'https://git.makerforce.io/beep/backend-subscribe.git'
        backend-transcription: 'https://git.makerforce.io/beep/backend-transcription.git'
  - name: docker
    image: plugins/docker
    settings:
      registry: registry.makerforce.io
      repo: registry.makerforce.io/beep/backend-publish
      context: backend-publish
      dockerfile: backend-publish/Dockerfile
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
---
kind: pipeline
name: backend-signal
clone:
  depth: 1
steps:
  - name: submodule
    image: plugins/git
    settings:
      recursive: true
      submodule_override:
        backend-auth: 'https://git.makerforce.io/beep/backend-auth.git'
        backend-bite: 'https://git.makerforce.io/beep/backend-bite.git'
        backend-core: 'https://git.makerforce.io/beep/backend-core.git'
        backend-heartbeat: 'https://git.makerforce.io/beep/backend-heartbeat.git'
        backend-login: 'https://git.makerforce.io/beep/backend-login.git'
        backend-protobuf: 'https://git.makerforce.io/beep/backend-protobuf.git'
        backend-publish: 'https://git.makerforce.io/beep/backend-publish.git'
        backend-signal: 'https://git.makerforce.io/beep/backend-signal.git'
        backend-store: 'https://git.makerforce.io/beep/backend-store.git'
        backend-subscribe: 'https://git.makerforce.io/beep/backend-subscribe.git'
        backend-transcription: 'https://git.makerforce.io/beep/backend-transcription.git'
  - name: docker
    image: plugins/docker
    settings:
      registry: registry.makerforce.io
      repo: registry.makerforce.io/beep/backend-signal
      context: backend-signal
      dockerfile: backend-signal/Dockerfile
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
---
kind: pipeline
name: backend-store
clone:
  depth: 1
steps:
  - name: submodule
    image: plugins/git
    settings:
      recursive: true
      submodule_override:
        backend-auth: 'https://git.makerforce.io/beep/backend-auth.git'
        backend-bite: 'https://git.makerforce.io/beep/backend-bite.git'
        backend-core: 'https://git.makerforce.io/beep/backend-core.git'
        backend-heartbeat: 'https://git.makerforce.io/beep/backend-heartbeat.git'
        backend-login: 'https://git.makerforce.io/beep/backend-login.git'
        backend-protobuf: 'https://git.makerforce.io/beep/backend-protobuf.git'
        backend-publish: 'https://git.makerforce.io/beep/backend-publish.git'
        backend-signal: 'https://git.makerforce.io/beep/backend-signal.git'
        backend-store: 'https://git.makerforce.io/beep/backend-store.git'
        backend-subscribe: 'https://git.makerforce.io/beep/backend-subscribe.git'
        backend-transcription: 'https://git.makerforce.io/beep/backend-transcription.git'
  - name: docker
    image: plugins/docker
    settings:
      registry: registry.makerforce.io
      repo: registry.makerforce.io/beep/backend-store
      context: backend-store
      dockerfile: backend-store/Dockerfile
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
---
kind: pipeline
name: backend-subscribe
clone:
  depth: 1
steps:
  - name: submodule
    image: plugins/git
    settings:
      recursive: true
      submodule_override:
        backend-auth: 'https://git.makerforce.io/beep/backend-auth.git'
        backend-bite: 'https://git.makerforce.io/beep/backend-bite.git'
        backend-core: 'https://git.makerforce.io/beep/backend-core.git'
        backend-heartbeat: 'https://git.makerforce.io/beep/backend-heartbeat.git'
        backend-login: 'https://git.makerforce.io/beep/backend-login.git'
        backend-protobuf: 'https://git.makerforce.io/beep/backend-protobuf.git'
        backend-publish: 'https://git.makerforce.io/beep/backend-publish.git'
        backend-signal: 'https://git.makerforce.io/beep/backend-signal.git'
        backend-store: 'https://git.makerforce.io/beep/backend-store.git'
        backend-subscribe: 'https://git.makerforce.io/beep/backend-subscribe.git'
        backend-transcription: 'https://git.makerforce.io/beep/backend-transcription.git'
  - name: docker
    image: plugins/docker
    settings:
      registry: registry.makerforce.io
      repo: registry.makerforce.io/beep/backend-subscribe
      context: backend-subscribe
      dockerfile: backend-subscribe/Dockerfile
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
---
kind: pipeline
name: backend-transcription
clone:
  depth: 1
steps:
  - name: submodule
    image: plugins/git
    settings:
      recursive: true
      submodule_override:
        backend-auth: 'https://git.makerforce.io/beep/backend-auth.git'
        backend-bite: 'https://git.makerforce.io/beep/backend-bite.git'
        backend-core: 'https://git.makerforce.io/beep/backend-core.git'
        backend-heartbeat: 'https://git.makerforce.io/beep/backend-heartbeat.git'
        backend-login: 'https://git.makerforce.io/beep/backend-login.git'
        backend-protobuf: 'https://git.makerforce.io/beep/backend-protobuf.git'
        backend-publish: 'https://git.makerforce.io/beep/backend-publish.git'
        backend-signal: 'https://git.makerforce.io/beep/backend-signal.git'
        backend-store: 'https://git.makerforce.io/beep/backend-store.git'
        backend-subscribe: 'https://git.makerforce.io/beep/backend-subscribe.git'
        backend-transcription: 'https://git.makerforce.io/beep/backend-transcription.git'
  - name: docker
    image: plugins/docker
    settings:
      registry: registry.makerforce.io
      repo: registry.makerforce.io/beep/backend-transcription
      context: backend-transcription
      dockerfile: backend-transcription/Dockerfile
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
---
kind: pipeline
name: deploy
clone:
  depth: 1
steps:
  - name: submodule
    image: plugins/git
    settings:
      recursive: true
      submodule_override:
        backend-auth: 'https://git.makerforce.io/beep/backend-auth.git'
        backend-bite: 'https://git.makerforce.io/beep/backend-bite.git'
        backend-core: 'https://git.makerforce.io/beep/backend-core.git'
        backend-heartbeat: 'https://git.makerforce.io/beep/backend-heartbeat.git'
        backend-login: 'https://git.makerforce.io/beep/backend-login.git'
        backend-protobuf: 'https://git.makerforce.io/beep/backend-protobuf.git'
        backend-publish: 'https://git.makerforce.io/beep/backend-publish.git'
        backend-signal: 'https://git.makerforce.io/beep/backend-signal.git'
        backend-store: 'https://git.makerforce.io/beep/backend-store.git'
        backend-subscribe: 'https://git.makerforce.io/beep/backend-subscribe.git'
        backend-transcription: 'https://git.makerforce.io/beep/backend-transcription.git'
  - name: copy-docker-compose
    image: appleboy/drone-scp
    settings:
      host: staging.beepvoice.app
      username: core
      key:
        from_secret: ssh_key
      source:
        - docker-compose.staging.yml
        - traefik.staging.toml
      target: /home/core/staging
    when:
      branch:
        - master
  - name: copy-migrations
    image: appleboy/drone-scp
    settings:
      host: staging.beepvoice.app
      username: core
      key:
        from_secret: ssh_key
      source:
        - backend-core/postgres/*
      target: /home/core/staging
    when:
      branch:
        - master
  - name: docker-compose-up
    image: appleboy/drone-ssh
    settings:
      host: staging.beepvoice.app
      username: core
      key:
        from_secret: ssh_key
      script:
        - >-
          cd /home/core/staging && /home/core/docker-compose -f
          docker-compose.staging.yml pull
        - >-
          cd /home/core/staging && /home/core/docker-compose -f
          docker-compose.staging.yml up -d
    when:
      branch:
        - master
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_beep
depends_on:
  - backend-auth
  - backend-bite
  - backend-core
  - backend-heartbeat
  - backend-login
  - backend-publish
  - backend-signal
  - backend-store
  - backend-subscribe
  - backend-transcription
