version: "3"
services:
  pg:
    build: ./backend-core/postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=core
    ports:
      - "5432:5432" # Close this for production
    networks:
      - pgnet
  nats:
    image: nats:latest
    ports: # Close these for production
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      - natsnet

  redis:
    image: redis:latest
    ports:
      - "6379:6379" # Close this for production
    networks:
      - redisnet

  core:
    build: ./backend-core
    tty: true
    restart: unless-stopped
    depends_on:
      - pg
    ports:
      - "10200:10200"
    networks:
      - pgnet
    command: -listen :10200 -postgres postgresql://root@pg:5432/core?sslmode=disable

  signal:
    build: ./backend-signal
    tty: true
    restart: unless-stopped
    environment:
      - PORT=10201
    ports:
      - "10201:10201"

  heartbeat:
    build: ./backend-heartbeat
    tty: true
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "10203:10203"
    networks:
      - redisnet
    command: -listen :10203 -redis redis:6379

  login:
    build: ./backend-login
    tty: true
    restart: unless-stopped
    ports:
      - "10204:10204"
    command: -listen :10204 -secret secret

  # Pipeline
  bite:
    build: ./backend-bite
    tty: true
    restart: unless-stopped
    depends_on:
      - nats
    ports:
      - "10202:10202"
    networks:
      - natsnet
    command: -listen :10202 -nats nats://nats:4222

  publish:
    build: ./backend-publish
    tty: true
    restart: unless-stopped
    depends_on:
      - nats
    ports:
      - "10205:10205"
    networks:
      - natsnet
    command: -listen :10205 -nats nats://nats:4222 -secret secret

  store:
    build: ./backend-store
    tty: true
    restart: unless-stopped
    depends_on:
      - nats
    networks:
      - natsnet
    command: -nats nats://nats:4222 -dbpath /tmp/badger

  subscribe:
    build: ./backend-subscribe
    tty: true
    restart: unless-stopped
    depends_on:
      - nats
    ports:
      - "10206:10206"
    networks:
      - natsnet
    command: -listen :10206 -nats nats://nats:4222

  transcription:
    build: ./backend-transcription
    tty: true
    restart: unless-stopped
    depends_on:
      - nats
    ports:
      - "10207:10207"
    networks:
      - natsnet
    command: -listen :10207 -nats nats://nats:4222 -api-key AIzaSyDxSXDefzw9gXCQaVzOCYlRn_vcC9Da9Q0

networks:
  pgnet:
  natsnet:
  redisnet:
