version: "3"
services:
  pg:
    build: ./backend-core/postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=core
    ports:
      - "5432:5432" # Close this for production
    networks:
      - pgnet
  nats:
    image: nats:latest
    ports: # Close these for production
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      - natsnet

  redis:
    image: redis:latest
    ports:
      - "6379:6379" # Close this for production
    networks:
      - redisnet

  core:
    build: ./backend-core
    tty: true
    restart: unless-stopped
    depends_on:
      - pg
    environment:
      - LISTEN=:10200
      - POSTGRES=postgresql://root@pg:5432/core?sslmode=disable
    ports:
      - "10200:10200"
    networks:
      - pgnet

  signal:
    build: ./backend-signal
    tty: true
    restart: unless-stopped
    environment:
      - PORT=10201
    ports:
      - "10201:10201"

  heartbeat:
    build: ./backend-heartbeat
    tty: true
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - LISTEN=:10203
      - REDIS=redis:6379
    ports:
      - "10203:10203"
    networks:
      - redisnet

  login:
    build: ./backend-login
    tty: true
    restart: unless-stopped
    environment:
      - LISTEN=:10204
      - SECRET=secret
    ports:
      - "10204:10204"

  # Pipeline
  bite:
    build: ./backend-bite
    tty: true
    restart: unless-stopped
    depends_on:
      - nats
    environment:
      - LISTEN=:10202
      - NATS=nats://nats:4222
    ports:
      - "10202:10202"
    networks:
      - natsnet

  publish:
    build: ./backend-publish
    tty: true
    restart: unless-stopped
    depends_on:
      - nats
    environment:
      - LISTEN=:10205
      - NATS=nats://nats:4222
      - SECRET=secret
    ports:
      - "10205:10205"
    networks:
      - natsnet

  store:
    build: ./backend-store
    tty: true
    restart: unless-stopped
    depends_on:
      - nats
    environment:
      - NATS=nats://nats:4222
      - DBPATH=/tmp/badger
    networks:
      - natsnet

  subscribe:
    build: ./backend-subscribe
    tty: true
    restart: unless-stopped
    depends_on:
      - nats
    environment:
      - LISTEN=:10206
      - NATS=nats://nats:4222
    ports:
      - "10206:10206"
    networks:
      - natsnet

  transcription:
    build: ./backend-transcription
    tty: true
    restart: unless-stopped
    depends_on:
      - nats
    environment:
      - LISTEN=:10207
      - NATS=nats://nats:4222
      - API_KEY=AIzaSyDxSXDefzw9gXCQaVzOCYlRn_vcC9Da9Q0
    ports:
      - "10207:10207"
    networks:
      - natsnet

networks:
  pgnet:
  natsnet:
  redisnet:
