# staging

[api]

dashboard = false

[acme]

email = "letsencrypt+alpha@beepvoice.app"
caServer = "https://acme-v02.api.letsencrypt.org/directory"
acmeLogging = true
storage = "acme-staging.json"
onHostRule = true
entryPoint = "https"
  [acme.httpChallenge]
  entryPoint = "http"

# funny, this doesn't work...
defaultEntryPoints = ["http", "https"]

[entryPoints]

  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.traefik]
  address = ":8080"

[file]

# Core

[backends.core]
  [backends.core.servers.one]
  url = "http://core"

[frontends.core]
backend = "core"
entrypoints = ["http", "https"]
  [frontends.core.auth.forward]
  address = "http://auth:10205/auth"
  [frontends.core.headers.customresponseheaders]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Headers = "Content-Type, Authorization, X-User-Claim"
  Access-Control-Allow-Credentials = "true"
  Access-Control-Allow-Methods = "GET, HEAD, POST, PUT, PATCH, DELETE"
  [frontends.core.routes.one]
  rule = "PathPrefixStrip: /core/"

# Signal

[backends.signal]
  [backends.signal.servers.one]
  url = "http://signal"

[frontends.signal]
backend = "signal"
entrypoints = ["http", "https"]
  [frontends.signal.auth.forward]
  address = "http://auth:10205/auth"
  [frontends.signal.headers.customresponseheaders]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Headers = "Content-Type, Authorization, X-User-Claim"
  Access-Control-Allow-Credentials = "true"
  Access-Control-Allow-Methods = "GET, HEAD, POST, PUT, PATCH, DELETE"
  [frontends.signal.routes.one]
  rule = "PathPrefixStrip: /signal/"

# Heartbeat

[backends.heartbeat]
  [backends.heartbeat.servers.one]
  url = "http://heartbeat"

[frontends.heartbeat]
backend = "heartbeat"
entrypoints = ["http", "https"]
  [frontends.heartbeat.auth.forward]
  address = "http://auth:10205/auth"
  [frontends.heartbeat.headers.customresponseheaders]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Headers = "Content-Type, Authorization, X-User-Claim"
  Access-Control-Allow-Credentials = "true"
  Access-Control-Allow-Methods = "GET, HEAD, POST, PUT, PATCH, DELETE"
  [frontends.heartbeat.routes.one]
  rule = "PathPrefixStrip: /heartbeat/"

# Bite

[backends.bite]
  [backends.bite.servers.one]
  url = "http://bite"

[frontends.bite]
backend = "bite"
entrypoints = ["http", "https"]
  [frontends.bite.auth.forward]
  address = "http://auth:10205/auth"
  [frontends.bite.headers.customresponseheaders]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Headers = "Content-Type, Authorization, X-User-Claim"
  Access-Control-Allow-Credentials = "true"
  Access-Control-Allow-Methods = "GET, HEAD, POST, PUT, PATCH, DELETE"
  [frontends.bite.routes.one]
  rule = "PathPrefixStrip: /bite/"

# Publish

[backends.publish]
  [backends.publish.servers.one]
  url = "http://publish"

[frontends.publish]
backend = "publish"
entrypoints = ["http", "https"]
  [frontends.publish.auth.forward]
  address = "http://auth:10205/auth"
  [frontends.publish.headers.customresponseheaders]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Headers = "Content-Type, Authorization, X-User-Claim"
  Access-Control-Allow-Credentials = "true"
  Access-Control-Allow-Methods = "GET, HEAD, POST, PUT, PATCH, DELETE"
  [frontends.publish.routes.one]
  rule = "PathPrefixStrip: /publish/"

# Subscribe

[backends.subscribe]
  [backends.subscribe.servers.one]
  url = "http://subscribe"

[frontends.subscribe]
backend = "subscribe"
entrypoints = ["http", "https"]
  [frontends.subscribe.auth.forward]
  address = "http://auth:10205/auth"
  [frontends.subscribe.headers.customresponseheaders]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Headers = "Content-Type, Authorization, X-User-Claim"
  Access-Control-Allow-Credentials = "true"
  Access-Control-Allow-Methods = "GET, HEAD, POST, PUT, PATCH, DELETE"
  [frontends.subscribe.routes.one]
  rule = "PathPrefixStrip: /subscribe/"

# Transcription

[backends.transcription]
  [backends.transcription.servers.one]
  url = "http://transcription"

[frontends.transcription]
backend = "transcription"
entrypoints = ["http", "https"]
  [frontends.transcription.auth.forward]
  address = "http://auth:10205/auth"
  [frontends.transcription.headers.customresponseheaders]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Headers = "Content-Type, Authorization, X-User-Claim"
  Access-Control-Allow-Credentials = "true"
  Access-Control-Allow-Methods = "GET, HEAD, POST, PUT, PATCH, DELETE"
  [frontends.transcription.routes.one]
  rule = "PathPrefixStrip: /transcription/"

# Login

[backends.login]
  [backends.login.servers.one]
  url = "http://login"

[frontends.login]
backend = "login"
entrypoints = ["login", "login_https"]
  [frontends.login.headers.customresponseheaders]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Headers = "Content-Type, Authorization"
  Access-Control-Allow-Credentials = "true"
  Access-Control-Allow-Methods = "GET, HEAD, POST, PUT, PATCH, DELETE"
  [frontends.login.routes.one]
  rule = "PathPrefixStrip: /"
