[api]
dashboard = true

[acme]
email = "letsencrypt+local@beepvoice.app"
caServer = "https://acme-v02.api.letsencrypt.org/directory"
acmeLogging = true
storage = "acme.json"
entryPoint = "https"
  [acme.dnsChallenge]
  provider = "digitalocean"
  delayBeforeCheck = 3

[entryPoints]
[entryPoints.http]
address = ":80"
  [entryPoints.http.auth.forward]
  address = "http://auth:10205/auth"
  trustForwardHeader = true
  authResponseHeaders = [ "X-User-Claim" ]
[entryPoints.https]
address = ":443"
  [entryPoints.https.tls]
  [entryPoints.https.auth.forward]
  address = "http://auth:10205/auth"
  trustForwardHeader = true
  authResponseHeaders = [ "X-User-Claim" ]

[entryPoints.login]
address = ":1837"
[entryPoints.login_https]
address = ":1838"
  [entryPoints.login_https.tls]
[entryPoints.traefik]
address = ":8080"

[file]
# Core
[backends.core]
  [backends.core.servers.one]
  url = "http://core"

[frontends.core]
backend = "core"
entrypoints = ["http", "https"]
  [frontends.core.headers.customresponseheaders]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Headers = "Content-Type, Authorization, X-User-Claim"
  Access-Control-Allow-Credentials = "true"
  Access-Control-Allow-Methods = "GET, HEAD, POST, PUT, PATCH, DELETE"
  [frontends.core.routes.one]
  rule = "PathPrefixStrip: /core/"

# Heartbeat
[backends.heartbeat]
  [backends.heartbeat.servers.one]
  url = "http://heartbeat"

[frontends.heartbeat]
backend = "heartbeat"
entrypoints = ["http", "https"]
  [frontends.heartbeat.headers.customresponseheaders]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Headers = "Content-Type, Authorization, X-User-Claim"
  Access-Control-Allow-Credentials = "true"
  Access-Control-Allow-Methods = "GET, HEAD, POST, PUT, PATCH, DELETE"
  [frontends.heartbeat.routes.one]
  rule = "PathPrefixStrip: /heartbeat/"

# pictures
[backends.pictures]
  [backends.pictures.servers.one]
  url = "http://pictures"

[frontends.pictures]
backend = "pictures"
entrypoints = ["http", "https"]
  [frontends.pictures.headers.customresponseheaders]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Headers = "Content-Type, Authorization, X-User-Claim"
  Access-Control-Allow-Credentials = "true"
  Access-Control-Allow-Methods = "GET, HEAD, POST, PUT, PATCH, DELETE"
  [frontends.pictures.routes.one]
  rule = "PathPrefixStrip: /pictures/"

# webrtc
[backends.webrtc]
  [backends.webrtc.servers.one]
  url = "http://webrtc"

[frontends.webrtc]
backend = "webrtc"
entrypoints = ["http", "https"]
  [frontends.webrtc.headers.customresponseheaders]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Headers = "Content-Type, Authorization, X-User-Claim"
  Access-Control-Allow-Credentials = "true"
  Access-Control-Allow-Methods = "GET, HEAD, POST, PUT, PATCH, DELETE"
  [frontends.webrtc.routes.one]
  rule = "PathPrefixStrip: /webrtc/"

# store
[backends.store]
  [backends.store.servers.one]
  url = "http://store"

[frontends.store]
backend = "store"
entrypoints = ["http", "https"]
  [frontends.store.headers.customresponseheaders]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Headers = "Content-Type, Authorization, X-User-Claim"
  Access-Control-Allow-Credentials = "true"
  Access-Control-Allow-Methods = "GET, HEAD, POST, PUT, PATCH, DELETE"
  [frontends.store.routes.one]
  rule = "PathPrefixStrip: /store/"

# login
[backends.login]
  [backends.login.servers.one]
  url = "http://login"

  [frontends.login]
  backend = "login"
  entrypoints = ["login", "login_https"]
  [frontends.login.headers.customresponseheaders]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Headers = "Content-Type, Authorization"
  Access-Control-Allow-Credentials = "true"
  Access-Control-Allow-Methods = "GET, HEAD, POST, PUT, PATCH, DELETE"
  [frontends.login.routes.one]
  rule = "PathPrefixStrip: /"
